# Generated by Django 4.0.4 on 2022-05-23 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_creatdate_alter_member_updatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='creatdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 23, 10, 59, 45, 543307)),
        ),
        migrations.AlterField(
            model_name='member',
            name='updatedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 23, 10, 59, 45, 543307)),
        ),
    ]
