# Generated by Django 4.0.4 on 2022-05-20 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeboard',
            name='f_creatdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 20, 12, 14, 28, 420458)),
        ),
        migrations.AlterField(
            model_name='freeboard',
            name='f_updatedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 20, 12, 14, 28, 420458)),
        ),
    ]
