# Generated by Django 4.0.4 on 2022-06-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('ex_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ex_name', models.CharField(max_length=300)),
                ('activity', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=2)),
                ('met', models.IntegerField(default=0)),
            ],
        ),
    ]
