# Generated by Django 4.0.4 on 2022-06-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dailyexercise',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('time', models.IntegerField(default=60)),
                ('ex_name', models.CharField(max_length=300)),
                ('burned_kcal', models.IntegerField(default=700)),
                ('goal_kcal', models.IntegerField(default=1000)),
            ],
        ),
    ]
